import { IChatObject } from "../TypeScriptObjs";
const sampleChatList: IChatObject[] = [
  {
    id: 1,
    name: "John",
    last_chat_date: "2024-03-27",
    unread_message_count: 2,
    last_message: "Hey, how's it going?",
  },
  {
    id: 2,
    name: "Alice",
    last_chat_date: "2024-03-26",
    unread_message_count: 0,
    last_message: "Sure, I'll see you then!",
  },
  {
    id: 3,
    name: "Bob",
    last_chat_date: "2024-03-27",
    unread_message_count: 1,
    last_message: "What time works for you?",
  },
  {
    id: 4,
    name: "Emily",
    last_chat_date: "2024-03-25",
    unread_message_count: 3,
    last_message: "Can you send me the details?",
  },
  {
    id: 5,
    name: "Mike",
    last_chat_date: "2024-03-26",
    unread_message_count: 0,
    last_message: "I'll check and let you know.",
  },
  {
    id: 6,
    name: "Sarah",
    last_chat_date: "2024-03-24",
    unread_message_count: 1,
    last_message: "See you tomorrow!",
  },
  {
    id: 7,
    name: "David",
    last_chat_date: "2024-03-26",
    unread_message_count: 2,
    last_message: "Thanks for the update.",
  },
  {
    id: 8,
    name: "Sophia",
    last_chat_date: "2024-03-25",
    unread_message_count: 0,
    last_message: "I'll get back to you soon.",
  },
  {
    id: 9,
    name: "James",
    last_chat_date: "2024-03-27",
    unread_message_count: 1,
    last_message: "Let me know if you need help.",
  },
  {
    id: 10,
    name: "Emma",
    last_chat_date: "2024-03-24",
    unread_message_count: 0,
    last_message: "Sure, I understand.",
  },
  {
    id: 11,
    name: "Liam",
    last_chat_date: "2024-03-25",
    unread_message_count: 2,
    last_message: "That sounds good to me.",
  },
  {
    id: 12,
    name: "Olivia",
    last_chat_date: "2024-03-26",
    unread_message_count: 0,
    last_message: "Let's discuss further.",
  },
  {
    id: 13,
    name: "Ben",
    last_chat_date: "2024-03-24",
    unread_message_count: 3,
    last_message: "I'm looking forward to it.",
  },
  {
    id: 14,
    name: "Ava",
    last_chat_date: "2024-03-27",
    unread_message_count: 0,
    last_message: "I'll keep you updated.",
  },
  {
    id: 15,
    name: "Ethan",
    last_chat_date: "2024-03-26",
    unread_message_count: 1,
    last_message: "Let me know your thoughts.",
  },
  {
    id: 16,
    name: "Mia",
    last_chat_date: "2024-03-25",
    unread_message_count: 0,
    last_message: "I'm glad to hear that.",
  },
  {
    id: 17,
    name: "Noah",
    last_chat_date: "2024-03-27",
    unread_message_count: 2,
    last_message: "Looking forward to it!",
  },
  {
    id: 18,
    name: "Isabella",
    last_chat_date: "2024-03-26",
    unread_message_count: 0,
    last_message: "Let me know if you need anything else.",
  },
  {
    id: 19,
    name: "Logan",
    last_chat_date: "2024-03-24",
    unread_message_count: 1,
    last_message: "I'll check and get back to you.",
  },
  {
    id: 20,
    name: "Charlotte",
    last_chat_date: "2024-03-25",
    unread_message_count: 0,
    last_message: "I understand your concerns.",
  },
  {
    id: 21,
    name: "Lucas",
    last_chat_date: "2024-03-26",
    unread_message_count: 3,
    last_message: "Let's schedule a meeting.",
  },
  {
    id: 22,
    name: "Amelia",
    last_chat_date: "2024-03-27",
    unread_message_count: 0,
    last_message: "Looking forward to your response.",
  },
  {
    id: 23,
    name: "Jackson",
    last_chat_date: "2024-03-25",
    unread_message_count: 2,
    last_message: "I'll let you know.",
  },
  {
    id: 24,
    name: "Evelyn",
    last_chat_date: "2024-03-24",
    unread_message_count: 0,
    last_message: "That works for me.",
  },
  {
    id: 25,
    name: "Jack",
    last_chat_date: "2024-03-26",
    unread_message_count: 1,
    last_message: "Let's proceed with that plan.",
  },
  {
    id: 26,
    name: "Harper",
    last_chat_date: "2024-03-27",
    unread_message_count: 0,
    last_message: "I'll get back to you soon.",
  },
  {
    id: 27,
    name: "Aiden",
    last_chat_date: "2024-03-25",
    unread_message_count: 2,
    last_message: "Thanks for the information.",
  },
  {
    id: 28,
    name: "Aria",
    last_chat_date: "2024-03-26",
    unread_message_count: 0,
    last_message: "I'll let you know once it's done.",
  },
  {
    id: 29,
    name: "Carter",
    last_chat_date: "2024-03-24",
    unread_message_count: 1,
    last_message: "Let's discuss this further.",
  },
  {
    id: 30,
    name: "Madison",
    last_chat_date: "2024-03-27",
    unread_message_count: 0,
    last_message: "I'll check and get back to you.",
  },
];

export { sampleChatList };
